


up:
	sudo docker compose up --build

down:
	sudo docker compose down

vol:
	sudo docker volume ls

img:
	sudo docker images

rem_img:
	sudo docker rmi --force $(sudo docker images -aq)

ps:
	sudo docker ps

del :
	sudo docker system prune -af