# Generated by Django 4.2.10 on 2024-11-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0010_user_info_scoor_alter_user_info_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='scoor',
        ),
        migrations.AddField(
            model_name='user_info',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
