# Generated by Django 4.2.10 on 2024-11-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermangement', '0005_remove_matchhistoric_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchhistoric',
            name='Type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
